package cli

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestParseEnvLocal_BasicKV is the floor: a single `KEY=VALUE` line
// with no surprises should round-trip verbatim.
func TestParseEnvLocal_BasicKV(t *testing.T) {
	path := writeEnvFile(t, "FOO=bar\n")
	got := parseEnvLocal(path)
	if len(got) != 1 || got[0] != "FOO=bar" {
		t.Errorf("parseEnvLocal = %v, want [FOO=bar]", got)
	}
}

// TestParseEnvLocal_ValuesWithShellMetachars is the REGRESSION GUARD
// for the v0.2.5 fix. The original failure mode was that the YAML
// post_create script ran `source .env.local` from bash, and bash
// choked on the first DSN line because `(` / `&` / `?` are shell
// metacharacters. The fix bypasses bash's parser by handing parsed
// env entries directly to exec.Cmd.Env, so any byte sequence in the
// value must survive verbatim.
func TestParseEnvLocal_ValuesWithShellMetachars(t *testing.T) {
	src := strings.Join([]string{
		`AUBA_API_DSN=root:@tcp(127.0.0.1:44075)/auba?parseTime=true&loc=UTC`,
		`AUBA_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_PORT=55075`,
		`AUBA_API_RDBURI=redis://127.0.0.1:55075/8`,
		`SHELL_LIKE=$(echo nope)`,
		`WITH_BACKTICKS=` + "`whoami`",
		`WITH_QUOTES="quoted value"`,
		`WITH_SINGLE_QUOTES='single quoted'`,
	}, "\n") + "\n"

	path := writeEnvFile(t, src)
	got := parseEnvLocal(path)
	want := []string{
		`AUBA_API_DSN=root:@tcp(127.0.0.1:44075)/auba?parseTime=true&loc=UTC`,
		`AUBA_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_PORT=55075`,
		`AUBA_API_RDBURI=redis://127.0.0.1:55075/8`,
		`SHELL_LIKE=$(echo nope)`,
		`WITH_BACKTICKS=` + "`whoami`",
		`WITH_QUOTES="quoted value"`,
		`WITH_SINGLE_QUOTES='single quoted'`,
	}
	if len(got) != len(want) {
		t.Fatalf("parseEnvLocal len = %d, want %d; got=%v", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

// TestParseEnvLocal_SkipsCommentsAndBlanks verifies the documented
// dropping behaviour — a `# Auto-generated by bough` header at the
// top of the file must not become an `# Auto-generated by bough` env
// key.
func TestParseEnvLocal_SkipsCommentsAndBlanks(t *testing.T) {
	src := strings.Join([]string{
		`# Auto-generated by bough`,
		``,
		`FOO=bar`,
		``,
		`# Trailing comment`,
		`BAZ=qux`,
		``,
	}, "\n")
	got := parseEnvLocal(writeEnvFile(t, src))
	want := []string{"FOO=bar", "BAZ=qux"}
	if len(got) != 2 || got[0] != want[0] || got[1] != want[1] {
		t.Errorf("parseEnvLocal = %v, want %v", got, want)
	}
}

// TestParseEnvLocal_DropsMalformed defends against a YAML author who
// pastes a stray heading or `KEY` (no value) into env_local — we drop
// the malformed line rather than panic.
func TestParseEnvLocal_DropsMalformed(t *testing.T) {
	src := "FOO=bar\nKEY_WITHOUT_EQUALS\n=value_without_key\nBAZ=qux\n"
	got := parseEnvLocal(writeEnvFile(t, src))
	want := []string{"FOO=bar", "BAZ=qux"}
	if len(got) != 2 || got[0] != want[0] || got[1] != want[1] {
		t.Errorf("parseEnvLocal = %v, want %v", got, want)
	}
}

// TestParseEnvLocal_MissingFile keeps the caller's post_create env
// the bare os.Environ() when no .env.local was rendered (e.g. a
// repository with neither env_local nor a db-provider role).
func TestParseEnvLocal_MissingFile(t *testing.T) {
	got := parseEnvLocal(filepath.Join(t.TempDir(), "no-such-file"))
	if got != nil {
		t.Errorf("parseEnvLocal(missing) = %v, want nil", got)
	}
}

// TestPostCreate_HeredocSeesEnvLocalVars is the end-to-end regression
// guard for the actual v0.2.5 bug: a bash `-c` post_create script
// must be able to expand `${BOUGH_REDIS_PORT}` (and friends) inside a
// heredoc *even when* the same .env.local also contains shell-hostile
// values like `AUBA_API_DSN=...tcp(...)/...?parseTime=true&loc=UTC`.
//
// Before the fix the script tried `source .env.local`, bash aborted
// the source on the DSN line's `(`, and `${BOUGH_REDIS_PORT}`
// substituted to empty — producing the literal `redis://127.0.0.1:/8`
// string that crashed the auba-api boot.
//
// After the fix bough hands parsed env entries directly to exec.Cmd
// .Env, so the bash script never invokes its own parser on the file.
// This test asserts the post-fix behaviour by running the same
// bash-with-heredoc pattern bough uses in production.
func TestPostCreate_HeredocSeesEnvLocalVars(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not on PATH")
	}

	dir := t.TempDir()
	envLocal := strings.Join([]string{
		`# Auto-generated by bough — fixture mirroring an auba-api worktree.`,
		`AUBA_API_DISABLE_PORT_FALLBACK=true`,
		`AUBA_API_DSN=root:@tcp(127.0.0.1:44075)/auba?parseTime=true&loc=UTC`,
		`AUBA_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_HOST=127.0.0.1`,
		`BOUGH_REDIS_PORT=55075`,
		`BOUGH_ELASTICSEARCH_URL=http://127.0.0.1:58075`,
	}, "\n") + "\n"
	envPath := filepath.Join(dir, ".env.local")
	if err := os.WriteFile(envPath, []byte(envLocal), 0o644); err != nil {
		t.Fatalf("write .env.local: %v", err)
	}

	// The same heredoc pattern an auba post_create entry would use,
	// minus the historical `set -a; source .env.local; set +a`
	// preamble that the v0.2.5 fix renders unnecessary.
	script := `cat >> .env.local <<EOF

# composition derived from bough plugin EnvVars
AUBA_API_RDBURI=redis://127.0.0.1:${BOUGH_REDIS_PORT}/8
AUBA_API_DLMURI=redis://127.0.0.1:${BOUGH_REDIS_PORT}/7
AUBA_API_ESURL=${BOUGH_ELASTICSEARCH_URL}
EOF`

	c := exec.CommandContext(context.Background(), "bash", "-c", script)
	c.Dir = dir
	// Mirror the production wiring: file env merged on top of
	// the inherited os.Environ.
	c.Env = append(os.Environ(), parseEnvLocal(envPath)...)
	if out, err := c.CombinedOutput(); err != nil {
		t.Fatalf("bash heredoc: %v\n%s", err, out)
	}

	final, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("read final .env.local: %v", err)
	}
	finalStr := string(final)

	wantSubstrings := []string{
		`AUBA_API_RDBURI=redis://127.0.0.1:55075/8`,
		`AUBA_API_DLMURI=redis://127.0.0.1:55075/7`,
		`AUBA_API_ESURL=http://127.0.0.1:58075`,
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(finalStr, want) {
			t.Errorf("appended .env.local missing %q\nfull contents:\n%s", want, finalStr)
		}
	}

	// And explicitly check the FAILURE pattern is gone — the original
	// bug appended `redis://127.0.0.1:/8` (port slot empty).
	if strings.Contains(finalStr, `redis://127.0.0.1:/8`) {
		t.Errorf("post-fix .env.local STILL contains the empty-port URI; bug regressed")
	}
}

func writeEnvFile(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), ".env.local")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write env file: %v", err)
	}
	return path
}
